# -*- coding: utf-8 -*-
"""xG_juve_spalletti.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHGwULLkzmG3vjZmqfpqaBrDxiUHncsj
"""

pip install soccerdata

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import soccerdata as sd

# ----------------------------
# Parametri principali
# ----------------------------
TEAM = "Juventus"
SPLIT_DATE = pd.Timestamp("2025-10-30")   # arrivo ufficiale di Spalletti
SEASON = "2025/2026"
ROLLING_WINDOW = 5

# ----------------------------
# Download dati da Understat tramite soccerdata
# ----------------------------
understat = sd.Understat(
    leagues="ITA-Serie A",
    seasons=SEASON
)

matches = understat.read_schedule().reset_index()

# Teniamo solo partite concluse con dati disponibili
matches = matches[(matches["is_result"] == True) & (matches["has_data"] == True)].copy()

# Parsing data
matches["date"] = pd.to_datetime(matches["date"])

# Filtro Juventus
juve = matches[
    (matches["home_team"] == TEAM) | (matches["away_team"] == TEAM)
].copy()

juve = juve.sort_values("date").reset_index(drop=True)

# ----------------------------
# Costruzione metriche Juventus
# ----------------------------
juve["is_home"] = juve["home_team"].eq(TEAM)

juve["opponent"] = np.where(
    juve["is_home"],
    juve["away_team"],
    juve["home_team"]
)

juve["venue"] = np.where(juve["is_home"], "H", "A")

juve["juve_xg"] = np.where(
    juve["is_home"],
    juve["home_xg"],
    juve["away_xg"]
).astype(float)

juve["juve_xga"] = np.where(
    juve["is_home"],
    juve["away_xg"],
    juve["home_xg"]
).astype(float)

juve["xg_diff"] = juve["juve_xg"] - juve["juve_xga"]

juve["period"] = np.where(
    juve["date"] < SPLIT_DATE,
    "Prima di Spalletti",
    "Dopo Spalletti"
)

juve["match_label"] = (
    juve["date"].dt.strftime("%d/%m") + " vs " + juve["opponent"] + " (" + juve["venue"] + ")"
)

# Medie mobili
juve["rolling_xg"] = juve["juve_xg"].rolling(ROLLING_WINDOW, min_periods=1).mean()
juve["rolling_xga"] = juve["juve_xga"].rolling(ROLLING_WINDOW, min_periods=1).mean()

# ----------------------------
# Tabella riassuntiva
# ----------------------------
summary = (
    juve.groupby("period")[["juve_xg", "juve_xga", "xg_diff"]]
    .agg(["mean", "median", "count"])
    .round(2)
)

print("\nRiepilogo Juventus xG prima/dopo Spalletti:\n")
print(summary)

# ----------------------------
# Grafico 1: andamento nel tempo
# ----------------------------
fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(juve["date"], juve["juve_xg"], marker="o", label="xG Juventus")
ax.plot(juve["date"], juve["juve_xga"], marker="o", label="xG concessi")

ax.plot(
    juve["date"],
    juve["rolling_xg"],
    linewidth=3,
    label=f"Media mobile xG ({ROLLING_WINDOW} partite)"
)

ax.plot(
    juve["date"],
    juve["rolling_xga"],
    linewidth=3,
    label=f"Media mobile xGA ({ROLLING_WINDOW} partite)"
)

ax.axvline(
    SPLIT_DATE,
    linestyle="--",
    linewidth=2,
    label="Arrivo Spalletti"
)

ax.set_title("Juventus - xG prima e dopo Spalletti (Serie A 2025/26)")
ax.set_xlabel("Data")
ax.set_ylabel("Expected Goals")
ax.legend()
ax.grid(True, alpha=0.3)

fig.autofmt_xdate()
plt.tight_layout()
plt.show()

# ----------------------------
# Grafico 2: confronto medie prima/dopo
# ----------------------------
summary_mean = (
    juve.groupby("period")[["juve_xg", "juve_xga", "xg_diff"]]
    .mean()
    .reindex(["Prima di Spalletti", "Dopo Spalletti"])
)

fig, ax = plt.subplots(figsize=(10, 6))
summary_mean.plot(kind="bar", ax=ax)

ax.set_title("Juventus - medie per partita prima vs dopo Spalletti")
ax.set_xlabel("")
ax.set_ylabel("Valore medio")
ax.legend(["xG creati", "xG concessi", "Differenziale xG"])
ax.grid(True, axis="y", alpha=0.3)

for container in ax.containers:
    ax.bar_label(container, fmt="%.2f", padding=3)

plt.tight_layout()
plt.show()

# ----------------------------
# Extra: tabella finale delle partite
# ----------------------------
cols = ["date", "opponent", "venue", "juve_xg", "juve_xga", "xg_diff", "period"]
print("\nDettaglio partite:\n")
print(juve[cols].round(2))



